export const screenPathMap: Record<string, string> = {
  landing: '/',
  login: '/login',
  'register-store': '/register-store',
  'register-driver': '/register-driver',
  home: '/home',
  'store-detail': '/store-detail',
  cart: '/cart',
  tracking: '/tracking',
  orders: '/orders',
  promotions: '/promotions',
  favorites: '/favorites',
  addresses: '/addresses',
  'personal-info': '/personal-info',
  'notification-settings': '/notification-settings',
  wallet: '/wallet',
  driver: '/driver',
  'store-admin': '/store-admin',
  admin: '/admin',
  profile: '/profile',
};
